### ISSUE TITLE
Subsetting doesn't seem to work

### ISSUE THREAD

**Issue by camertron** [rillig/sfntly#2]
Hey @rillig, thanks for all your work maintaining sfntly!

I'm having trouble subsetting the Noto Sans font (attached). I'm running it through the included (C++) subset tool, but it spits out a file that's the exact same size as the original. Any idea what could be going wrong? Thanks!

[NotoSansCJKjp-Regular.otf.zip](https://github.com/rillig/sfntly/files/1402710/NotoSansCJKjp-Regular.otf.zip)

**Comment by rillig** [comment]
Hey @camertron,

I don't have any idea about the C++ part of this project, in fact, I haven't even tried to build it. I just played around a little with the Java part, and poof, I became the "official" maintainer of the whole project.

So I'm afraid I cannot help you in this regard. Just the obvious tips: Add some `printf` logging to `subsetter.cc` and to all `TODO` lines on the way from `main` to the subsetter class. I hope that helps. Or you might try whether the Java subsetter is more mature. But that also has lots of `TODO` comments.
